[book]
title = "From Zero to QED"
description = "An informal introduction to formality in Lean 4"
authors = ["Stephen Diehl"]
language = "en"
src = "src"

[build]
build-dir = "book/pdf"
create-missing = true

[output.typst]

[output.typst.output]
format = "typst"

[output.typst.style]
text-font = "New Computer Modern"
text-size = "11pt"
paper = "us-letter"
